- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Download artifacts from artifactory
      get_url:
        url:
        dest: 
        url_username: 
        url_password: 
